### PR TITLE
Sensor tests

### PR DESCRIPTION
**Pull request by davidedelvento**
A directory with some tests of alternative sensors, namely EAITRCA6 and QRE1113

### CODE REVIEW

**Comment by davidedelvento** [comment]
@jkominek what do you think of this PR? Given that I am planning to post more data like this at https://github.com/davidedelvento/Mybrid/tree/main/data perhaps this can be dropped and/or moved there. On the other hand, even if not merged, it is some data that people browsing this repo will find and might find useful.

What do you prefer? Have you settled on the CNY70 or are you keeping the QRE1113 option open?

**Comment by jkominek** [comment]
> @jkominek what do you think of this PR? Given that I am planning to post more data like this at https://github.com/davidedelvento/Mybrid/tree/main/data perhaps this can be dropped and/or moved there. On the other hand, even if not merged, it is some data that people browsing this repo will find and might find useful.

I'd been thinking about it and hadn't really decided. When I made my "analyses" directory in the repo, I put my stuff in a "jkominek" subdirectory with the idea that other work could go in there, in directories named by the contributor.

> What do you prefer? Have you settled on the CNY70 or are you keeping the QRE1113 option open?

I ordered enough CNY70 to finish my build off, since availability is becoming limited, and I believe it will be more than sufficient for the task. That said, I'll pick up some QRE1113 with my next Digikey order, and I'm willing to lay out a version of the sensorboards to use it. The pinout appears to be the same, just needs a different footprint. I assume you're interested in the SMT version?

**Comment by davidedelvento** [comment]
> That said, I'll pick up some QRE1113 with my next Digikey order, and I'm willing to lay out a version of the sensorboards to use it. The pinout appears to be the same, just needs a different footprint. 

Awesome. Thanks!!

> I assume you're interested in the SMT version?

Yes, to have them professionally assembled. I was mulling if we shouldn't ask SparkFun if they are interested: they already have similar products and unlike other vendors who do only PCB building-and-assembly SF could make the product available for the general public without custom orders. I think we are reaching a critical mass for pianos and a 4- or 6- board sensor would be useful for robotics too, hence they might be willing to do it. As you noticed with the pico efforts, one goal of mine is to have a super-easy version for anybody (not just die-hard tinkerers) and having the necessary sensors available at SF would be a big step towards that goal. What do you think?

**Comment by davidedelvento** [comment]
No need to merge this one, closing

**Pull request closed without merging**
